# -*- coding: utf-8 -*-
"""Assignment-10/03(Armstrong Numbers).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yn6KilJsSCgDHDIayLSiuBFVlGN4YYr1

`Assignment - 10/03 (Armstrong Numbers)`

**Task:**

Find out if a given number is an "Armstrong Number".

-An n-digit number that is the sum of the nth powers of its digits is called an n-Armstrong number. 
Examples :

1-371 = 3 **
3 + 7 **
3 + 1 **
3;

2-9474 = 9 **
4 + 4 **
4 + 7 **
4 + 4 **
4;

3-93084 = 9 **
5 + 3 **
5 + 0 **
5 + 8 **
5 + 4 **
5.


-Write a Python program that;

1.takes a positive integer number from the user,

2.checks the entered number if it is Armstrong,

3.consider the negative, float and any entries other than 
numeric values then display a warning message to the user.

Examples

Sample inputs	         
Outputs

407	                   
407 is an Armstrong number

5	                     
5 is an Armstrong number

-153	                 
It is an invalid entry. Don't use non-numeric, float, or negative values!

153.87 or 153,87	     
It is an invalid entry. Don't use non-numeric, float, or negative values!


one	                   
It is an invalid entry. Don't use non-numeric, float, or negative values!

 121	                 
 121 is not an Armstrong number
"""

number = input("Enter a positive number:")
total = 0
if not number.isdigit() :
  print("It is an invalid entry. Don't use non-numeric, float, or negative values!")
elif int(number) >= 0 :
  for i in number :
    total += int(i) ** len(number)
  if int(number) == total :
    print(" is an Armstrong number")
  else :
    print(" is not an Armstrong number")