# -*- coding: utf-8 -*-
"""Assignment-10/04(Is It a Prime Number?).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6ajExSq6d_Uxr5pxfCOZm1vsdHg6nU6

`**Assignment - 10/04 (Is It a Prime Number?)**`

**Task** : Write a program that takes a number from the user      and prints the result to check if it is a prime number.

The examples of the desired output are as follows :

input →  19 ⇉ output : 19 is a prime number

input →  10 ⇉ output : 10 is not a prime number
"""

n = int(input("Enter a positive number:"))
count = 0
for i in range(2,n) :
  if n % i == 0 :
    count += 1
if n==0 or n == 1 or count > 0 :
  print(n, "is not a prime number")
else :
  print(n, "is a prime number")

print(0xA + 0xB + 0xC)

str1 = "hello"
str2 = ","
str3 = "world"
print(str1[-1:])
str1 = "world"

print(r"\nhello")

print("new" "line")

print("new" "line" "end" 3)

print("new" "line" "end", 3)

def team_names(*teams) :
    print('The teams in Premier League are :')
    for i in teams :
        print('-', i)

team_names('Liverpool', 'M.United', 'M.City', 'Arsenal')

def make_sentence(**kwargs):
    result = ""
    # Iterating over the Python kwargs dictionary
    for i in kwargs.values():
        result += i
    return result

print(make_sentence(a="I ", b="love ", c="Clarusway!"))