# -*- coding: utf-8 -*-
"""Assignment-10/05(Fibonacci Numbers).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQzwwK4-QZ7eJq0qfXxeG7x-m2vAViQ5

Assignment - 10/05 (Fibonacci Numbers)

Task : Create a list consisting of Fibonacci numbers from 1 to 55 using control flow statements.

The desired output is like :

fibonacci →  [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
"""

liste =[0,1] # Fibonacci Numbers 0 ve 1'den başlayarak önceki iki sayının toplamıdır. 
fibonacci =[1] # ilk elemanı 0+1= 1 dir. ve i > 1 için sıra başlar  ni = n(i-1)+n(i-2) bulunur.
i = 2
while fibonacci[-1] < 55 :
  x = liste[i-1] + liste[i-2] 
  liste.append(x)
  fibonacci.append(x)
  i +=1
print(fibonacci)