# -*- coding: utf-8 -*-
"""Assignment - 10/08 (Letters Count).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oGxRX7OE2UOQyxhyG3Md3Xc19CydD2zI

Assignment - 10/08 (Letters Count)

Task:

Count the number of each letter in a sentence.
-The department you work for undertook a project construction that makes word / text analysis. You are asked to calculate the number of letters or any chars in the sentences entered under this project.

-Write a Python program that;
1-takes a sentence from the user,
2-counts the number of each letter of the sentence,
3-collects the letters/chars as a key and the counted numbers as a value in a dictionary.

Examples

Sample inputs	: hippo runs to us!	

Outputs :

{'s': 2, 'r': 1, 't': 1, 'h': 1, 'n': 1, 
'i': 1, 'u': 2, 'o': 2, 'p': 2, ' ': 3, '!': 1}
"""

sentence =input("Enter a sentence:").lower()
result ={}
for i in list(sentence):
  result[i]=list(sentence).count(i)
print(result)