# -*- coding: utf-8 -*-
"""Assignment-10/02(Covid-19 Risk with If Statements).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oXCMmY74YP6Fty8_sJnsXNu_MiJ99lu

Assignment - 10/02 (Covid-19 Risk with If Statements)

Problem :

-Task : Estimating the risk of death from coronavirus. Write a program that;

-Takes "Yes" or "No" from the user as an answer to the following questions :

-Are you a cigarette addict older than 75 years old? Variable → age

-Do you have a severe chronic disease? Variable → chronic

-Is your immune system too weak? Variable → immune

Set a logical algorithm using boolean logic operators (and/or) and use if-statements with the given variables in order to print out us a message : "You are in risky group"(if True ) or "You are not in risky group" (if False).

age =  # can be assigned only True/False

chronic =  # can be assigned only True/False

immune =  # can be assigned only True/False

risk = ?
"""

age = input("Are you a cigarette addict older than 75 years old? (Yes or No):").title().strip()
chronic = input("Do you have a severe chronic disease? (Yes or No) :").title().strip()
immune = input("Is your immune system too weak?(Yes or No) :").title().strip()

if age == "Yes" or chronic == "Yes" or immune == "Yes" :
  print("You are  in risky group")
elif age == "No" and chronic == "No" and immune == "No" :
  print("You are not in risky group")
else :
  print ("Enter answers are not Yes or No")