# -*- coding: utf-8 -*-
"""Assignment _10_01(Password Reminder).py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UZHuzJVru_LXWZudxsfujiMTPpKqB6hu

# Assignment - 10/01 (Password Reminder) 

Task : Let's say; you left a message in the past that prints a password you need. To see the password you wrote, you need to enter your name and the program should recognize you.

Write a program that 

1.Takes the first name from the user and compares it to yours,

2.Then if the name the user entered is the same as yours, print out such as : "Hello, Joseph! The password is : W@12",

3.If the name the user entered is not the same as yours, print out such as : "Hello, Amina! See you later."
"""

name = "dursun"
first_name = input("Please, Enter your first name :").lower().strip()
if name == first_name :
    print("Hello, Dursun! The password is : drsahin55")
else:
    print("Hello, {}! See you later.".format(first_name.title()))



